# trabalhando com looping
- name: creating a loop
  hosts: all
  tasks:
   - name: assure epel-release
     yum:
      name: epel-release
     when: ansible_os_family == "RedHat"

   - name: installing packages
     package:
      name: "{{ item }}"
     with_items:
       - vim
       - cowsay
       - figlet
