- name: exercicio1
  hosts: all
  tasks:
   - name: criando users
     user:
      name: "{{item}}"
      shell: /bin/bash
     with_items:
       - developer
       - bruno
       - suporte


   - name: instalando pacotes no debian
     package:
      name: "{{item.pacote}}"
     when: ansible_os_family == item.distro
     with_items:
       - { pacote: git, distro: Debian }
       - { pacote: vim, distro: Debian }
       - { pacote: figlet, distro: Debian }
       - { pacote: epel-release, distro: RedHat }
       - { pacote: vim, distro: RedHat }
       - { pacote: git, distro: RedHat }


   - name: criando diretorio no tmp
     file:
      path: "{{item.arquivo}}"
      state: "{{item.tipo}}"
     with_items:
       - { arquivo: /tmp/devops, tipo: directory }

   - name: colocando conteudo no arquivo
     blockinfile:
      create: yes
      path: /tmp/devops/file
      block: |
       sou devops
       na 4linux
       com um bloco de conteudo em um arquivo
